# Generated by Django 2.2 on 2020-09-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
